name: Alistar CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: |
        ./test_build/test_suite.out
        ./node_build/node_test.out
        ./list_build/list_test.out

    # Optional: Upload artifacts
    - name: Create release artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        mkdir alistar_binaries
        cp build/test_build/test_suite.out alistar_binaries/
        cp build/node_build/node_test.out alistar_binaries/
        cp build/list_build/list_test.out alistar_binaries/
        zip -r alistar_binaries.zip alistar_binaries/

    - name: Upload artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: alistar-binaries
        path: alistar_binaries.zip
