name: Publish to GitHub Packages
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    # Build binaries
    - name: Build
      run: |
        cmake -B build
        cmake --build build
    
    # Package binaries
    - name: Package
      run: |
        mkdir -p alistar/lib
        cp build/*/*.out alistar/lib/
        
    # Publish to GitHub Packages
    - name: Publish to GitHub Packages
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
